name: Happy Coding
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
permalink: /:categories/:slug
gems:
  - jemoji
  - jekyll-last-modified-at
  
defaults:
 -
    scope:
      path: ""
    values:
      test: "testing variables"
